name: digilib
description: "A new Flutter project."
publish_to: "none"

version: 1.2.4

environment:
  sdk: ">=3.2.2 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.6
  dio: ^5.4.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  google_fonts: ^6.1.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  carousel_slider: ^4.2.1
  flutter_svg: ^2.0.9
  flutter_staggered_grid_view: ^0.7.0
  persistent_bottom_nav_bar: ^5.0.2
  # device_info_plus: ^10.1.0
  sqflite: ^2.3.0
  sqflite_common_ffi: ^2.3.0
  readmore: ^2.2.0
  syncfusion_flutter_pdfviewer: ^24.1.45
  syncfusion_flutter_core: ^24.1.45
  path: ^1.8.3
  url_launcher: ^6.2.4
  cached_network_image: ^3.3.1
  screenshot_callback: ^3.0.1
  dropdown_button2: ^2.3.9
  sqlite3_flutter_libs: ^0.5.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/icons/
    - assets/logo/
    - assets/illustrations/

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700

flutter_launcher_icons:
  android: false # ganti ke true jika ingin modifikasi android app icon
  ios: true
  min_sdk_android: 19
  remove_alpha_ios: true
  image_path: "assets/logo/orbit-digilib-logo-o-white.png"
  adaptive_icon_foreground: "assets/logo/orbit-digilib-logo-o-foreground.png"
  adaptive_icon_background: "assets/logo/orbit-digilib-logo-o-background.png"

# dependency_overrides:
#   win32: 3.1.4
